// <auto-generated />
namespace ProjectFilm_CNPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createdv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdv2));
        
        string IMigrationMetadata.Id
        {
            get { return "202405270653176_createdv2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
