//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFilm_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheLoai
    {
        public int id { get; set; }
        public int MaPhim { get; set; }
        public string TenTheLoai { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual Phim Phim { get; set; }
    }
}
